name: Bug report
description: Issues and bugs for Frosty
labels: 
- bug
- pending reproduction

body:
- type: markdown
  attributes:
    value: Before filing this bug, [please check if it hasn't already been reported](https://github.com/wannkunstbeikor/Test/labels/bug). If it has, please add useful information to the existing issue instead.

- type: input
  attributes:
    label: Operating System
    placeholder: Window 10 64bit, Build 18363
  validations:
    required: true

- type: input
  attributes:
    label: Frosty Version
    placeholder: 1.0.6.1
    description: To get the version information, press "Help" on the menu bar and press "About".
  validations:
    required: true
    
- type: dropdown
  attributes:
    label: Frosty
    options:
      - Editor
      - ModManager
  validations:
    required: true
    
- type: dropdown
  attributes:
    label: Games
    multiple: true
    options:
      - Anthem
      - Battlefield 1
      - Battlefield 4
      - Battlefield 2042
      - Battlefield Hardline
      - Battlefield V
      - DragonAge Inquisition
      - Fifa 17
      - Fifa 18
      - Fifa 19
      - Fifa 20
      - Fifa 21
      - Fifa 22
      - Madden 19
      - Madden 20
      - Madden 22
      - Madden 23
      - MassEffect Andromeda
      - MirrorsEdge Catalyst
      - Need for Speed
      - Need for Speed Online
      - Need for Speed Edge
      - Need for Speed Heat
      - Need for Speed Rivals
      - Plant vs Zombies GW1
      - Plant vs Zombies GW2
      - Plant vs Zombies BfN
      - Star Wars Battlefront
      - Star Wars Battlefront II
      - Star Wars Squadrons
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the issue
    description: Please describe the issue you are experiencing here.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: Please describe in small and detailed steps on how to reproduce the issue.
    placeholder: |
      Steps required to reproduce the issue. 
      1.
      2.
      3.
  validations:
    required: true

- type: textarea
  attributes:
    label: Attachments
    description: If you can provide crashdumps or screenshots that help to investigate the issue please provide them.
    placeholder: Drag and drop files here to add them
  validations:
    required: false
